server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/craftbox_eureka?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true